
import nbtlib
from pathlib import Path

import random

class Block():
    """
    This class stores block information.
    """

    def __init__(self, name: str, x: int, y: int, z: int) -> None:
        self.x = x
        self.y = y
        self.z = z
        self.state = {}
        self.name = name
        self.id = ""
        if "[" in name:
            self.id = name.split("[")[0]
            state_str = name.split("[")[1].split("]")[0]
            for value in state_str.split(","):
                self.state[value.split("=")[0]] = value.split("=")[1]
        else:
            self.id = name

    def get_block_state_str(self):
        output = "{"
        for key, value in self.state.items():
            output += "{}:{}".format(key,value)
        output += "}"
        return output


class BlockGroup():
    """
    This class holds a collection of blocks and provides methods to export them to a text file.
    """
    def __init__(self, path: str | None, offset: list[int] | None):
        self.blocks = []
        x = 0
        y = 0
        z = 0
        if offset != None and len(offset) == 3:
            x = offset[0]
            y = offset[1]
            z = offset[2]
        if path != None:
            p = Path(path)
            if p.suffix.lower() == ".txt":
                self.load_txt(path)
            elif p.suffix.lower() == ".schem":
                self.load_schem(path,x,y,z)

    def get_list(self):
        return self.blocks

    def random(self):
        random.shuffle(self.blocks)

    def append(self, block_group: BlockGroup):
        self.blocks.extend(block_group.blocks)

    def sort_by_axis(self, axis: str):
        """
        Sort the block group in ascending order along the specified axis. Elements with identical axis-values are internally shuffled randomly.

        Args:
            axis : (str) 
                Sorting axis. Only "x"/"y"/"z" are permitted. Illegal input defaults to "y".
        """
        if axis not in ("x", "y", "z"):
            axis = "y"

        group_dict: dict[int, list[Block]] = {}
        for blk in self.blocks:
            key_val = getattr(blk, axis)
            if key_val not in group_dict:
                group_dict[key_val] = []
            group_dict[key_val].append(blk)

        result: list[Block] = []
        for val in sorted(group_dict.keys()):
            group = group_dict[val]
            random.shuffle(group)
            result.extend(group)
        self.blocks = result
    
    def load_schem(self, schem_path: str, offset_x=0, offset_y=0, offset_z=0, skip_air=True):
        """
        Read and translate Schem v3 file (often generated by WorldEdit)
        """
        nbt_file = nbtlib.load(schem_path)["Schematic"]
        root = nbt_file

        width = root["Width"]
        height = root["Height"]
        length = root["Length"]

        palette = root["Blocks"]["Palette"]
        palette_map = {idx: str(name) for idx, name in enumerate(palette)}
        block_data = root["Blocks"]["Data"]

        out_list = []
        for y in range(height):
            for z in range(length):
                for x in range(width):
                    index = y * width * length + z * width + x
                    pal_idx = block_data[index]
                    block_name = palette_map[pal_idx]

                    if skip_air and block_name == "minecraft:air":
                        continue

                    world_x = offset_x + x
                    world_y = offset_y + y
                    world_z = offset_z + z
                    out_list.append(Block(block_name,world_x,world_y,world_z))

        self.blocks = out_list

    def load_txt(self, txt_path):
        out_list = []
        with open(txt_path,"r") as f:
            for line in f:
                parts = line.split(" ")
                out_list.append(Block(parts[0],int(parts[1]),int(parts[2]),int(parts[3])))
        self.blocks = out_list

    def save_as_txt(self, txt_path):
        with open(txt_path,"w") as f:
            for block in self.blocks:
                f.write("{} {} {} {}".format(block.name, block.x, block.y, block.z))

        


