
import os
from pathlib import Path
from .logger import Logger

def backup_folder_name(original_path: str | Path, logger: Logger) -> bool:
    """

    If the target folder already exists, append the suffix _OLD to its name. In case of naming conflicts, sequentially try appending _OLD2, _OLD3, and so on until an available name is found.
    
    Args:
        target_path: (str | Path)
        logger: (Logger) 

    """
    p = Path(original_path)
    if not p.is_dir():
        return True

    base_parent = p.parent
    base_name = p.name
    new_name = f"{base_name}_OLD"
    new_p = base_parent / new_name
    counter = 2

    while new_p.exists():
        new_name = f"{base_name}_OLD{counter}"
        new_p = base_parent / new_name
        counter += 1

    try:
        p.rename(new_p)
        if logger:
            logger.log_warn(f"旧数据包文件夹已更名备份: {p} → {new_p}")
        return True
    except Exception as e:
        if logger:
            logger.log_error(f"备份旧文件夹失败: {str(e)}")
        return False



class DatapackManager():
    """

    This class manages datapack, including writing and removing files.

    """

    def __init__(self, datapack_name: str, datapack_version: int, logger: Logger):
        """
        Args:
            datapack_name : (str)
                Name used for the datapack folder and namespace.

            version : (int)
                Pack format version written into pack.mcmeta.
        """
        self.datapack_name = datapack_name
        self.datapack_version = datapack_version

        self.is_backuped = backup_folder_name(os.path.join("output",self.datapack_name), logger)

        if self.is_backuped:
            self.write_mcmeta()
            self.create_load_function()
            self.create_tick_function()


    
    def write_file(self, path: str, content: str|list[str]):
        """
        Args:
            path : (str)
                Target file path. Using os.path.join() is recommended.
            
            content : (str) or (list[str])
                File text content. If a list is provided, each element will be written line-by-line in order.
        """
        path = os.path.join("output", path)
        os.makedirs(os.path.dirname(path), exist_ok=True)

        content_str = ""

        if type(content) == list:
            content_str = "\n".join(content)
        else:
            content_str = str(content)

        with open(path, "a", encoding="utf-8") as file:
            file.write(content_str)



    def write_function_file(self, path: str, content: str|list[str]):
        """
        Args:
            path : (str)
                Relative path starting from the function folder. Using os.path.join() is recommended.
            
            content : (str) | (list[str])
                File text content. If a list is provided, each element will be written line-by-line in order.
        """
        real_path = os.path.join(self.datapack_name, "data", self.datapack_name, "function", path)
        self.write_file(real_path, content)



    def write_mcmeta(self):
        """
        Create the pack.mcmeta using the datapack version provided during initialization.
        """
        mcmeta_content = '''{{
            "pack": {{
                "description": "Generated by VanillaAnimationGenerator.",
                "min_format": {0},
                "max_format": {0}
            }}
        }}'''.format(self.datapack_version)
        file_path = os.path.join(self.datapack_name, "pack.mcmeta")

        self.write_file(file_path, mcmeta_content)



    def create_load_function(self):
        """
        Create load.mcfunction file and its corresponding function tag within the minecraft namespace.
        """
        self.write_function_file("load.mcfunction", "")

        json_content = '''{{
                "values": ["{}:load"]
                }}'''.format(self.datapack_name)
        json_path = os.path.join(self.datapack_name, "data", "minecraft", "tags","function","load.json")
        
        if not os.path.exists(json_path):
            self.write_file(json_path,json_content)
        


    def create_tick_function(self):
        """
        Create tick.mcfunction file and its corresponding function tag within the minecraft namespace.
        """
        self.write_function_file("tick.mcfunction", "")

        json_content = '''{{
                "values": ["{}:tick"]
                }}'''.format(self.datapack_name)
        json_path = os.path.join(self.datapack_name, "data", "minecraft", "tags","function","tick.json")

        if not os.path.exists(json_path):
            self.write_file(json_path,json_content)


    



        