
import os

class DatapackManager():
    """

    This class manages datapack, including writing and removing files.

    """

    def __init__(self, datapack_name: str, datapack_version: int):
        """
        Args:
            datapack_name : (str)
                Name used for the datapack folder and namespace.

            version : (int)
                Pack format version written into pack.mcmeta.
        """
        self.datapack_name = datapack_name
        self.datapack_version = datapack_version

        self.write_mcmeta()
        self.create_load_function()
        self.create_tick_function()


    
    def write_file(self, path: str, content: str|list[str]):
        """
        Args:
            path : (str)
                Target file path. Using os.path.join() is recommended.
            
            content : (str) or (list[str])
                File text content. If a list is provided, each element will be written line-by-line in order.
        """
        path = os.path.join("output", path)
        os.makedirs(os.path.dirname(path), exist_ok=True)

        content_str = ""

        if type(content) == list:
            content_str = "\n".join(content)
        else:
            content_str = str(content)

        with open(path, "a", encoding="utf-8") as file:
            file.write(content_str)



    def write_function_file(self, path: str, content: str|list[str]):
        """
        Args:
            path : (str)
                Relative path starting from the function folder. Using os.path.join() is recommended.
            
            content : (str) | (list[str])
                File text content. If a list is provided, each element will be written line-by-line in order.
        """
        real_path = os.path.join(self.datapack_name, "data", self.datapack_name, "function", path)
        self.write_file(real_path, content)



    def write_mcmeta(self):
        """
        Create the pack.mcmeta using the datapack version provided during initialization.
        """
        mcmeta_content = '''{{
            "pack": {{
                "description": "Generated by VanillaAnimationGenerator.",
                "min_format": {0},
                "max_format": {0}
            }}
        }}'''.format(self.datapack_version)
        file_path = os.path.join(self.datapack_name, "pack.mcmeta")

        self.write_file(file_path, mcmeta_content)



    def create_load_function(self):
        """
        Create load.mcfunction file and its corresponding function tag within the minecraft namespace.
        """
        self.write_function_file("load.mcfunction", "")

        json_content = '''{{
                "values": ["{}:load"]
                }}'''.format(self.datapack_name)
        json_path = os.path.join(self.datapack_name, "data", "minecraft", "tags","function","load.json")
        
        if not os.path.exists(json_path):
            self.write_file(json_path,json_content)
        


    def create_tick_function(self):
        """
        Create tick.mcfunction file and its corresponding function tag within the minecraft namespace.
        """
        self.write_function_file("tick.mcfunction", "")

        json_content = '''{{
                "values": ["{}:tick"]
                }}'''.format(self.datapack_name)
        json_path = os.path.join(self.datapack_name, "data", "minecraft", "tags","function","tick.json")

        if not os.path.exists(json_path):
            self.write_file(json_path,json_content)


    



        